org: josephyi
app: nikola
service: nikola

frameworkVersion: ">=1.4.0 <2.0.0"
package:
  exclude:
    - .git/**
    - package.json
    - "*.test.js"
    - env.yml
    - env.yml.template
    - README.md
    - yarn.lock
    - __mocks__/**
    - .jshintrc

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, 'us-west-2'}

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.region}
  memorySize: 128
  timeout: 60
  iamRoleStatements:
    - Effect: Allow
      Action:
        - iot:*
      Resource: "*"
  tracing:
    lambda: ${file(env.yml):${self:custom.stage}.tracing}

functions:
  nikola:
    handler: index.handler
    events: ${file(env.yml):${self:custom.stage}.iotevent}
    environment: ${file(env.yml):${self:custom.stage}.variables}
